### ISSUE TITLE
Disable the automatic device registration modal when a mobile user visits zerobase.io for the first time

### ISSUE THREAD

**Issue by eriksogn** [zerobase-io/smart-tracing#193] opened 2020-04-03 23:35 UTC
I think this is a big turn-off. Currently this registration modal is first thing a new user sees on our page, even before they have a chance to see "privacy first" or read any of our great content. My concern is this will get a lot of people to close their browser window in fear instead of exploring what zerobase is.

I imagine, for example, a tired political leader at the end of the day checking us out for the first time on their phone - and before they know who or what we are, we're asking to automatically register their device.

Another example is that a concerned or confused individual could see us on a sign, and want to contact us or give feedback - and now they need to make this choice before they get to the feedback form.

#### For discussion
* What is the purpose of having a device registered if they are not at a touchpoint or scanning?
* What is the benefit of a call to action to register their device if they are not scanning?
* At what points do we want to automatically register a device?
* What are the disadvantages to removing this automatic registration?
* If we remove this automatic registration, what work gets to be done to re-enable this where appropriate?

![IMG_5329](https://user-images.githubusercontent.com/5020291/78412793-8ba5da00-75c9-11ea-8222-3f8b9f44f986.png)

**Comment by aronszanto** [comment] 2020-04-04 02:13
+1 to this, it's not legally required. per discussion with john we should just delete

**Comment by JohnCLo** [comment] 2020-04-04 11:33
This is a duplicate of #159 
Before making an issue head on over to https://github.com/zerobase-io/smart-tracing/projects/5 to do a brief check if it exists. TY

**Closed** 2020-04-04 16:37 UTC
